namespace AFTRS.Infrastructure;

public static class UiText
{
    public static string Language(HttpRequest request)
    {
        var value = request.Cookies["AFTRS.Language"];
        return string.Equals(value, "ar", StringComparison.OrdinalIgnoreCase) ? "ar" : "en";
    }

    public static string Theme(HttpRequest request)
    {
        var value = request.Cookies["AFTRS.Theme"];
        return string.Equals(value, "dark", StringComparison.OrdinalIgnoreCase) ? "dark" : "light";
    }

    public static string T(HttpRequest request, string key) => T(Language(request), key);

    public static string T(string language, string key)
    {
        if (!string.Equals(language, "ar", StringComparison.OrdinalIgnoreCase))
            return English.TryGetValue(key, out var en) ? en : key;

        return Arabic.TryGetValue(key, out var ar) ? ar : English.TryGetValue(key, out var fallback) ? fallback : key;
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Dashboard"] = "Dashboard",
        ["FinancialOperations"] = "Financial Operations",
        ["DataImport"] = "Data Import",
        ["RunEngine"] = "Run Engine",
        ["Discrepancies"] = "Discrepancies",
        ["Intelligence"] = "Intelligence",
        ["Templates"] = "Templates",
        ["HelpCsvGuide"] = "Help / CSV Guide",
        ["AdminSecurity"] = "Admin & Security",
        ["SecurityLogs"] = "Security Logs",
        ["AuditTrail"] = "Audit Trail",
        ["Settings"] = "Settings",
        ["SystemAdministrator"] = "System Administrator",
        ["FinancialManager"] = "Financial Manager",
        ["SettingsTitle"] = "Settings",
        ["SettingsSubtitle"] = "Manage your profile, display theme, and interface language.",
        ["LoggedInUser"] = "Logged-in User",
        ["Username"] = "Username",
        ["Role"] = "Role",
        ["UserId"] = "User ID",
        ["AccountStatus"] = "Account Status",
        ["Active"] = "Active",
        ["Locked"] = "Locked",
        ["Preferences"] = "Interface Preferences",
        ["Theme"] = "Theme",
        ["LightMode"] = "Light Mode",
        ["DarkMode"] = "Dark Mode",
        ["Language"] = "Language",
        ["English"] = "English",
        ["Arabic"] = "Arabic",
        ["SaveSettings"] = "Save Settings",
        ["SettingsSaved"] = "Settings saved.",
        ["ThemeHelp"] = "Dark and light mode are stored for this browser.",
        ["LanguageHelp"] = "Arabic switches the interface direction to right-to-left.",
        ["Unauthorized"] = "Unable to load the logged-in user. Please sign in again."
        , ["LoginTitle"] = "AFTRS Login"
        , ["Login"] = "Login"
        , ["AuthorizedUseOnly"] = "Authorized Use Only"
        , ["EmailAddress"] = "Email Address"
        , ["Password"] = "Password"
        , ["RememberMe"] = "Remember me"
        , ["ForgotPassword"] = "Forgot Password?"
        , ["AccessDenied"] = "Access Denied"
        , ["NoPermission"] = "You do not have permission to access this resource."
        , ["ReturnDashboard"] = "Return to dashboard"
        , ["CreateAccount"] = "Create Account"
        , ["ConfirmPassword"] = "Confirm Password"
        , ["DefaultManagerRole"] = "New accounts are assigned the Financial Manager role by default."
        , ["Register"] = "Register"
        , ["ReconciliationDashboard"] = "Reconciliation Dashboard"
        , ["ExportPdf"] = "Export PDF"
        , ["ExportExcel"] = "Export Excel"
        , ["Categorize"] = "Categorize"
        , ["RunReconciliationEngine"] = "Run Reconciliation Engine"
        , ["ProcessingTransactions"] = "Processing Transactions..."
        , ["AutoReconciled"] = "Auto Reconciled"
        , ["ManualReconciled"] = "Manual Reconciled"
        , ["Discrepancy"] = "Discrepancy"
        , ["Date"] = "Date"
        , ["Description"] = "Description"
        , ["Amount"] = "Amount"
        , ["Source"] = "Source"
        , ["Category"] = "Category"
        , ["Status"] = "Status"
        , ["InternalLedger"] = "Internal Ledger"
        , ["BankStatement"] = "Bank Statement"
        , ["UploadLedger"] = "Upload Ledger"
        , ["UploadBankStatement"] = "Upload Bank Statement"
        , ["MaxUploadNotice"] = "Maximum file size:"
        , ["PerUploadFormats"] = "per upload. Accepted formats:"
        , ["ViewCsvGuide"] = "View CSV format guide"
        , ["RecentUploads"] = "Recent Uploads"
        , ["NoFilesUploaded"] = "No files uploaded yet."
        , ["FileName"] = "File Name"
        , ["Type"] = "Type"
        , ["UploadedAt"] = "Uploaded At"
        , ["DiscrepancyWorkbench"] = "Discrepancy Resolution Workbench"
        , ["LedgerDiscrepancies"] = "Ledger Discrepancies"
        , ["BankDiscrepancies"] = "Bank Discrepancies"
        , ["SelectedLedgerId"] = "Selected Ledger ID"
        , ["BankId"] = "Bank ID"
        , ["ForceMatch"] = "Force Match"
        , ["AuditCommentRequired"] = "Audit Comment Required"
        , ["ManualLinkWarning"] = "You are manually linking two discrepancy records. This action will be logged permanently."
        , ["ReasonManualMatch"] = "Reason for manual match"
        , ["Cancel"] = "Cancel"
        , ["ConfirmLog"] = "Confirm & Log"
        , ["SecurityLogsTitle"] = "System Security Logs (UC-15)"
        , ["FilterByDate"] = "Filter by Date"
        , ["FilterByUser"] = "Filter by User"
        , ["AllUsers"] = "All users"
        , ["ApplyFilter"] = "Apply Filter"
        , ["Clear"] = "Clear"
        , ["Timestamp"] = "Timestamp"
        , ["User"] = "User"
        , ["IpAddress"] = "IP Address"
        , ["Action"] = "Action"
        , ["Success"] = "Success"
        , ["Failed"] = "Failed"
        , ["FinancialAuditTrail"] = "Financial Audit Trail"
        , ["Note"] = "Note"
        , ["AuditTrailNote"] = "This record is append-only. Manual matches require a justification comment."
        , ["Transaction"] = "Transaction"
        , ["OldStatus"] = "Old Status"
        , ["NewStatus"] = "New Status"
        , ["Justification"] = "Justification"
        , ["CreateTemplate"] = "Create Template"
        , ["NewTemplate"] = "New Template"
        , ["Frequency"] = "Frequency"
        , ["NextRun"] = "Next Run"
        , ["NextRunDate"] = "Next Run Date"
        , ["DescriptionName"] = "Description Name"
        , ["AmountLyd"] = "Amount (LYD)"
        , ["Select"] = "Select..."
        , ["Monthly"] = "Monthly"
        , ["Weekly"] = "Weekly"
        , ["Save"] = "Save"
        , ["TemplatesHelp"] = "Templates are used to recognize recurring transactions and auto-apply categories during processing."
        , ["StrategicTitle"] = "Strategic Intelligence"
        , ["ExportBudgetPdf"] = "Export Budget PDF"
        , ["ChartsNote"] = "Charts update from reconciled ledger data"
        , ["SetMonthlyBudgets"] = "Set Monthly Budgets"
        , ["CategoryName"] = "Category Name"
        , ["Month"] = "Month"
        , ["Year"] = "Year"
        , ["LimitLyd"] = "Limit (LYD)"
        , ["SaveBudget"] = "Save Budget"
        , ["HeuristicsDictionary"] = "Heuristics Dictionary"
        , ["HeuristicsHelp"] = "Auto-categorization uses category keyword rules against transaction descriptions."
        , ["KeywordRule"] = "Keyword Rule"
        , ["SaveCategoryRule"] = "Save Category Rule"
        , ["NoCategoryRules"] = "No category rules defined yet."
        , ["CashFlowTitle"] = "Cash Flow - History & Projection (FR-20)"
        , ["Projection"] = "Projection"
        , ["Months3"] = "3 months"
        , ["Months6"] = "6 months"
        , ["HistoricalProjected"] = "Historical / Projected"
        , ["BudgetActualTitle"] = "Budget vs. Actual Spending (UC-12)"
        , ["NoBudgets"] = "No budgets defined for this month."
        , ["OverBudget"] = "Over Budget"
        , ["ManagerDashboard"] = "Financial Manager Dashboard"
        , ["OperationalOverview"] = "Operational Overview & Session Management"
        , ["RoleLabel"] = "Role"
        , ["PendingDiscrepancies"] = "Pending Discrepancies"
        , ["RequiresManualResolution"] = "Requires manual resolution"
        , ["OpenImport"] = "Open Import"
        , ["OpenWorkbench"] = "Open Workbench"
        , ["QuickActions"] = "Quick Actions"
        , ["RunReconciliation"] = "Run Reconciliation"
        , ["ViewIntelligence"] = "View Intelligence"
        , ["SystemProgress"] = "System Progress"
        , ["TotalTransactions"] = "Total Transactions"
        , ["Reconciled"] = "Reconciled"
        , ["MatchRate"] = "Match Rate"
        , ["Ledger"] = "Ledger"
        , ["Bank"] = "Bank"
        , ["Records"] = "records"
        , ["AdminDashboard"] = "System Admin Dashboard"
        , ["SecurityMonitoring"] = "Security Monitoring & Audit Compliance"
        , ["TotalRegisteredUsers"] = "Total Registered Users"
        , ["RecentSecurityEvents"] = "Recent Security Events"
        , ["TotalSessionsProcessed"] = "Total Sessions Processed"
        , ["StandaloneNote"] = "Standalone file processor (no batch archive in this build)"
        , ["ComplianceControls"] = "Compliance Controls"
        , ["TrackAccess"] = "Track all login attempts and IP addresses"
        , ["ViewImmutable"] = "View immutable record of manual matches"
        , ["Error"] = "Error"
        , ["ErrorOccurred"] = "An error occurred while processing your request."
        , ["RequestId"] = "Request ID"
        , ["PrivacyPolicy"] = "Privacy Policy"
        , ["PrivacyText"] = "Use this page to detail your site's privacy policy."
        , ["AccountLockedAdmin"] = "Account locked. Contact the System Administrator."
        , ["AccountLockedAttempts"] = "Account locked. Too many failed attempts."
        , ["InvalidLogin"] = "Invalid login attempt."
        , ["PasswordComplexity"] = "Password must be at least 8 characters and include uppercase, lowercase, a digit, and a symbol."
        , ["UsernameExists"] = "Username already exists."
        , ["NoFileUploaded"] = "No file uploaded."
        , ["FileTooLarge"] = "File '{0}' exceeds the 25 MB size limit."
        , ["InvalidSourceType"] = "Invalid source type."
        , ["InvalidFileType"] = "Invalid file type. Only .csv and .xlsx are supported."
        , ["NoNewRows"] = "No new rows imported (all rows may be duplicates)."
        , ["ImportedRecords"] = "Imported {0} records from '{1}' ({2})."
        , ["EngineComplete"] = "Engine complete: {0} transaction pairs reconciled, {1} categorized."
        , ["CategorizationComplete"] = "Categorization complete: {0} transactions updated."
        , ["BudgetSaved"] = "Budget target saved."
        , ["CategoryNameRequired"] = "Category name is required."
        , ["CategoryExists"] = "Category already exists."
        , ["CategoryRuleSaved"] = "Category keyword rule saved."
        , ["InvalidMonth"] = "Invalid month."
        , ["InvalidYear"] = "Invalid year."
        , ["JustificationMandatory"] = "Justification is mandatory."
        , ["BothDiscrepancies"] = "Both transactions must be discrepancies."
        , ["CategoryRequired"] = "Category is required."
        , ["DescriptionNameRequired"] = "DescriptionName is required."
        , ["AmountGreaterThanZero"] = "Amount must be greater than zero."
        , ["TemplateCreated"] = "Template created."
        , ["Logout"] = "Logout"
        , ["CommandCenter"] = "AFTRS Command Center"
        , ["SecurityOperations"] = "Security Operations"
        , ["SecurePortal"] = "AFTRS Secure Portal"
        , ["Enrollment"] = "AFTRS Enrollment"
    };

    private static readonly IReadOnlyDictionary<string, string> Arabic = new Dictionary<string, string>
    {
        ["Dashboard"] = "لوحة التحكم",
        ["FinancialOperations"] = "العمليات المالية",
        ["DataImport"] = "استيراد البيانات",
        ["RunEngine"] = "تشغيل المحرك",
        ["Discrepancies"] = "الفروقات",
        ["Intelligence"] = "التحليل المالي",
        ["Templates"] = "القوالب",
        ["HelpCsvGuide"] = "المساعدة / دليل CSV",
        ["AdminSecurity"] = "الإدارة والأمان",
        ["SecurityLogs"] = "سجلات الأمان",
        ["AuditTrail"] = "مسار التدقيق",
        ["Settings"] = "الإعدادات",
        ["SystemAdministrator"] = "مدير النظام",
        ["FinancialManager"] = "المدير المالي",
        ["SettingsTitle"] = "الإعدادات",
        ["SettingsSubtitle"] = "إدارة بيانات الحساب والمظهر ولغة الواجهة.",
        ["LoggedInUser"] = "بيانات المستخدم الحالي",
        ["Username"] = "اسم المستخدم",
        ["Role"] = "الدور",
        ["UserId"] = "رقم المستخدم",
        ["AccountStatus"] = "حالة الحساب",
        ["Active"] = "نشط",
        ["Locked"] = "مقفل",
        ["Preferences"] = "تفضيلات الواجهة",
        ["Theme"] = "المظهر",
        ["LightMode"] = "الوضع الفاتح",
        ["DarkMode"] = "الوضع الداكن",
        ["Language"] = "اللغة",
        ["English"] = "الإنجليزية",
        ["Arabic"] = "العربية",
        ["SaveSettings"] = "حفظ الإعدادات",
        ["SettingsSaved"] = "تم حفظ الإعدادات.",
        ["ThemeHelp"] = "يتم حفظ الوضع الداكن والفاتح لهذا المتصفح.",
        ["LanguageHelp"] = "تجعل العربية اتجاه الواجهة من اليمين إلى اليسار.",
        ["Unauthorized"] = "تعذر تحميل بيانات المستخدم الحالي. يرجى تسجيل الدخول مرة أخرى."
        , ["LoginTitle"] = "تسجيل الدخول إلى AFTRS"
        , ["Login"] = "تسجيل الدخول"
        , ["AuthorizedUseOnly"] = "للاستخدام المصرح فقط"
        , ["EmailAddress"] = "البريد الإلكتروني"
        , ["Password"] = "كلمة المرور"
        , ["RememberMe"] = "تذكرني"
        , ["ForgotPassword"] = "هل نسيت كلمة المرور؟"
        , ["AccessDenied"] = "تم رفض الوصول"
        , ["NoPermission"] = "ليست لديك صلاحية للوصول إلى هذا المورد."
        , ["ReturnDashboard"] = "العودة إلى لوحة التحكم"
        , ["CreateAccount"] = "إنشاء حساب"
        , ["ConfirmPassword"] = "تأكيد كلمة المرور"
        , ["DefaultManagerRole"] = "يتم تعيين الحسابات الجديدة بدور المدير المالي افتراضياً."
        , ["Register"] = "تسجيل"
        , ["ReconciliationDashboard"] = "لوحة المطابقة المالية"
        , ["ExportPdf"] = "تصدير PDF"
        , ["ExportExcel"] = "تصدير Excel"
        , ["Categorize"] = "تصنيف"
        , ["RunReconciliationEngine"] = "تشغيل محرك المطابقة"
        , ["ProcessingTransactions"] = "جاري معالجة المعاملات..."
        , ["AutoReconciled"] = "مطابقة تلقائية"
        , ["ManualReconciled"] = "مطابقة يدوية"
        , ["Discrepancy"] = "فرق"
        , ["Date"] = "التاريخ"
        , ["Description"] = "الوصف"
        , ["Amount"] = "المبلغ"
        , ["Source"] = "المصدر"
        , ["Category"] = "الفئة"
        , ["Status"] = "الحالة"
        , ["InternalLedger"] = "السجل الداخلي"
        , ["BankStatement"] = "كشف البنك"
        , ["UploadLedger"] = "رفع السجل"
        , ["UploadBankStatement"] = "رفع كشف البنك"
        , ["MaxUploadNotice"] = "الحد الأقصى لحجم الملف:"
        , ["PerUploadFormats"] = "لكل رفع. الصيغ المقبولة:"
        , ["ViewCsvGuide"] = "عرض دليل CSV"
        , ["RecentUploads"] = "آخر الملفات المرفوعة"
        , ["NoFilesUploaded"] = "لا توجد ملفات مرفوعة بعد."
        , ["FileName"] = "اسم الملف"
        , ["Type"] = "النوع"
        , ["UploadedAt"] = "وقت الرفع"
        , ["DiscrepancyWorkbench"] = "منصة حل الفروقات"
        , ["LedgerDiscrepancies"] = "فروقات السجل"
        , ["BankDiscrepancies"] = "فروقات البنك"
        , ["SelectedLedgerId"] = "رقم السجل المحدد"
        , ["BankId"] = "رقم البنك"
        , ["ForceMatch"] = "فرض المطابقة"
        , ["AuditCommentRequired"] = "تعليق التدقيق مطلوب"
        , ["ManualLinkWarning"] = "أنت تربط سجلين من الفروقات يدوياً. سيتم تسجيل هذا الإجراء بشكل دائم."
        , ["ReasonManualMatch"] = "سبب المطابقة اليدوية"
        , ["Cancel"] = "إلغاء"
        , ["ConfirmLog"] = "تأكيد وتسجيل"
        , ["SecurityLogsTitle"] = "سجلات أمان النظام (UC-15)"
        , ["FilterByDate"] = "تصفية حسب التاريخ"
        , ["FilterByUser"] = "تصفية حسب المستخدم"
        , ["AllUsers"] = "كل المستخدمين"
        , ["ApplyFilter"] = "تطبيق التصفية"
        , ["Clear"] = "مسح"
        , ["Timestamp"] = "الوقت"
        , ["User"] = "المستخدم"
        , ["IpAddress"] = "عنوان IP"
        , ["Action"] = "الإجراء"
        , ["Success"] = "نجاح"
        , ["Failed"] = "فشل"
        , ["FinancialAuditTrail"] = "مسار التدقيق المالي"
        , ["Note"] = "ملاحظة"
        , ["AuditTrailNote"] = "هذا السجل للإضافة فقط. المطابقات اليدوية تتطلب تعليق تبرير."
        , ["Transaction"] = "المعاملة"
        , ["OldStatus"] = "الحالة السابقة"
        , ["NewStatus"] = "الحالة الجديدة"
        , ["Justification"] = "التبرير"
        , ["CreateTemplate"] = "إنشاء قالب"
        , ["NewTemplate"] = "قالب جديد"
        , ["Frequency"] = "التكرار"
        , ["NextRun"] = "التشغيل التالي"
        , ["NextRunDate"] = "تاريخ التشغيل التالي"
        , ["DescriptionName"] = "اسم الوصف"
        , ["AmountLyd"] = "المبلغ (LYD)"
        , ["Select"] = "اختر..."
        , ["Monthly"] = "شهري"
        , ["Weekly"] = "أسبوعي"
        , ["Save"] = "حفظ"
        , ["TemplatesHelp"] = "تستخدم القوالب للتعرف على المعاملات المتكررة وتطبيق الفئات تلقائياً أثناء المعالجة."
        , ["StrategicTitle"] = "التحليل المالي الاستراتيجي"
        , ["ExportBudgetPdf"] = "تصدير الميزانية PDF"
        , ["ChartsNote"] = "يتم تحديث الرسوم من بيانات السجل المطابقة"
        , ["SetMonthlyBudgets"] = "تحديد الميزانيات الشهرية"
        , ["CategoryName"] = "اسم الفئة"
        , ["Month"] = "الشهر"
        , ["Year"] = "السنة"
        , ["LimitLyd"] = "الحد (LYD)"
        , ["SaveBudget"] = "حفظ الميزانية"
        , ["HeuristicsDictionary"] = "قاموس التصنيف"
        , ["HeuristicsHelp"] = "يستخدم التصنيف التلقائي قواعد الكلمات المفتاحية للفئات مقابل أوصاف المعاملات."
        , ["KeywordRule"] = "قاعدة الكلمة المفتاحية"
        , ["SaveCategoryRule"] = "حفظ قاعدة الفئة"
        , ["NoCategoryRules"] = "لا توجد قواعد فئات بعد."
        , ["CashFlowTitle"] = "التدفق النقدي - التاريخ والتوقع (FR-20)"
        , ["Projection"] = "التوقع"
        , ["Months3"] = "3 أشهر"
        , ["Months6"] = "6 أشهر"
        , ["HistoricalProjected"] = "تاريخي / متوقع"
        , ["BudgetActualTitle"] = "الميزانية مقابل الإنفاق الفعلي (UC-12)"
        , ["NoBudgets"] = "لا توجد ميزانيات محددة لهذا الشهر."
        , ["OverBudget"] = "تجاوز الميزانية"
        , ["ManagerDashboard"] = "لوحة المدير المالي"
        , ["OperationalOverview"] = "نظرة تشغيلية وإدارة الجلسة"
        , ["RoleLabel"] = "الدور"
        , ["PendingDiscrepancies"] = "الفروقات المعلقة"
        , ["RequiresManualResolution"] = "يتطلب حلاً يدوياً"
        , ["OpenImport"] = "فتح الاستيراد"
        , ["OpenWorkbench"] = "فتح منصة العمل"
        , ["QuickActions"] = "إجراءات سريعة"
        , ["RunReconciliation"] = "تشغيل المطابقة"
        , ["ViewIntelligence"] = "عرض التحليل"
        , ["SystemProgress"] = "تقدم النظام"
        , ["TotalTransactions"] = "إجمالي المعاملات"
        , ["Reconciled"] = "مطابقة"
        , ["MatchRate"] = "نسبة المطابقة"
        , ["Ledger"] = "السجل"
        , ["Bank"] = "البنك"
        , ["Records"] = "سجلات"
        , ["AdminDashboard"] = "لوحة مدير النظام"
        , ["SecurityMonitoring"] = "مراقبة الأمان والامتثال"
        , ["TotalRegisteredUsers"] = "إجمالي المستخدمين المسجلين"
        , ["RecentSecurityEvents"] = "أحدث أحداث الأمان"
        , ["TotalSessionsProcessed"] = "إجمالي الجلسات المعالجة"
        , ["StandaloneNote"] = "معالج ملفات مستقل (لا يوجد أرشيف دفعات في هذا الإصدار)"
        , ["ComplianceControls"] = "ضوابط الامتثال"
        , ["TrackAccess"] = "تتبع كل محاولات الدخول وعناوين IP"
        , ["ViewImmutable"] = "عرض السجل غير القابل للتعديل للمطابقات اليدوية"
        , ["Error"] = "خطأ"
        , ["ErrorOccurred"] = "حدث خطأ أثناء معالجة طلبك."
        , ["RequestId"] = "رقم الطلب"
        , ["PrivacyPolicy"] = "سياسة الخصوصية"
        , ["PrivacyText"] = "استخدم هذه الصفحة لتفصيل سياسة الخصوصية الخاصة بالموقع."
        , ["AccountLockedAdmin"] = "الحساب مقفل. تواصل مع مدير النظام."
        , ["AccountLockedAttempts"] = "تم قفل الحساب بسبب كثرة المحاولات الفاشلة."
        , ["InvalidLogin"] = "محاولة تسجيل دخول غير صحيحة."
        , ["PasswordComplexity"] = "يجب أن تكون كلمة المرور 8 أحرف على الأقل وتحتوي على حرف كبير وحرف صغير ورقم ورمز."
        , ["UsernameExists"] = "اسم المستخدم موجود بالفعل."
        , ["NoFileUploaded"] = "لم يتم رفع أي ملف."
        , ["FileTooLarge"] = "الملف '{0}' يتجاوز حد الحجم 25 MB."
        , ["InvalidSourceType"] = "نوع المصدر غير صحيح."
        , ["InvalidFileType"] = "نوع الملف غير صحيح. الصيغ المدعومة فقط .csv و .xlsx."
        , ["NoNewRows"] = "لم يتم استيراد صفوف جديدة (قد تكون كل الصفوف مكررة)."
        , ["ImportedRecords"] = "تم استيراد {0} سجل من '{1}' ({2})."
        , ["EngineComplete"] = "اكتمل المحرك: تمت مطابقة {0} أزواج معاملات، وتم تصنيف {1}."
        , ["CategorizationComplete"] = "اكتمل التصنيف: تم تحديث {0} معاملات."
        , ["BudgetSaved"] = "تم حفظ هدف الميزانية."
        , ["CategoryNameRequired"] = "اسم الفئة مطلوب."
        , ["CategoryExists"] = "الفئة موجودة بالفعل."
        , ["CategoryRuleSaved"] = "تم حفظ قاعدة الكلمة المفتاحية للفئة."
        , ["InvalidMonth"] = "الشهر غير صحيح."
        , ["InvalidYear"] = "السنة غير صحيحة."
        , ["JustificationMandatory"] = "التبرير مطلوب."
        , ["BothDiscrepancies"] = "يجب أن تكون المعاملتان من الفروقات."
        , ["CategoryRequired"] = "الفئة مطلوبة."
        , ["DescriptionNameRequired"] = "اسم الوصف مطلوب."
        , ["AmountGreaterThanZero"] = "يجب أن يكون المبلغ أكبر من صفر."
        , ["TemplateCreated"] = "تم إنشاء القالب."
        , ["Logout"] = "تسجيل الخروج"
        , ["CommandCenter"] = "مركز قيادة AFTRS"
        , ["SecurityOperations"] = "عمليات الأمان"
        , ["SecurePortal"] = "بوابة AFTRS الآمنة"
        , ["Enrollment"] = "تسجيل AFTRS"
    };
}
